on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "teste minimo ${{ inputs.image_name }}"
